-- Safo B2B MySQL Dump
-- Generated: 2026-07-25 01:26:08

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

TRUNCATE TABLE `users`;
INSERT INTO `users` (`id`,`name`,`phone`,`email`,`password`,`type`,`store_name`,`store_type`,`avatar`,`city`,`area`,`address`,`otp_code`,`otp_expires_at`,`fcm_token`,`is_verified`,`is_active`,`last_login_at`,`remember_token`,`created_at`,`updated_at`,`deleted_at`) VALUES ('1','مدير النظام','770000001',NULL,'$2y$12$M.l0m0emJLV8IW8IOaN34.LjJxI0B/Xl8QZoBN8NvBrwDjxb7XatS','admin',NULL,NULL,NULL,'صنعاء',NULL,NULL,NULL,NULL,NULL,'1','1',NULL,NULL,'2026-07-25 01:25:38','2026-07-25 01:25:38',NULL);
INSERT INTO `users` (`id`,`name`,`phone`,`email`,`password`,`type`,`store_name`,`store_type`,`avatar`,`city`,`area`,`address`,`otp_code`,`otp_expires_at`,`fcm_token`,`is_verified`,`is_active`,`last_login_at`,`remember_token`,`created_at`,`updated_at`,`deleted_at`) VALUES ('2','محمد_supply','771000001',NULL,'$2y$12$igGVwHErXxM17gQQzsvG.OGFEYCVr8X2j3rwY2rpDHtSbeHZUTw62','supplier','سوبر ماركت الرائد','supermarket',NULL,'صنعاء','الحصبة',NULL,NULL,NULL,NULL,'1','1',NULL,NULL,'2026-07-25 01:25:38','2026-07-25 01:25:38',NULL);
INSERT INTO `users` (`id`,`name`,`phone`,`email`,`password`,`type`,`store_name`,`store_type`,`avatar`,`city`,`area`,`address`,`otp_code`,`otp_expires_at`,`fcm_token`,`is_verified`,`is_active`,`last_login_at`,`remember_token`,`created_at`,`updated_at`,`deleted_at`) VALUES ('3','أحمد_supply','771000002',NULL,'$2y$12$xFHuXDYKRXpZGKdQUbqA4e423l1vRHzj8QZYmXBgbnNnwjDd.k.jK','supplier','بقالة الخير','grocery',NULL,'عدن','كريتر',NULL,NULL,NULL,NULL,'1','1',NULL,NULL,'2026-07-25 01:25:39','2026-07-25 01:25:39',NULL);
INSERT INTO `users` (`id`,`name`,`phone`,`email`,`password`,`type`,`store_name`,`store_type`,`avatar`,`city`,`area`,`address`,`otp_code`,`otp_expires_at`,`fcm_token`,`is_verified`,`is_active`,`last_login_at`,`remember_token`,`created_at`,`updated_at`,`deleted_at`) VALUES ('4','علي_supply','771000003',NULL,'$2y$12$wskvUn0gCkkFmFv1urxDPOELbQOV.rR.6h8/uoJCFnoOc6WjBFJZy','supplier','مطعم اليمان','restaurant',NULL,'تعز','القاهرة',NULL,NULL,NULL,NULL,'1','1',NULL,NULL,'2026-07-25 01:25:39','2026-07-25 01:25:39',NULL);
INSERT INTO `users` (`id`,`name`,`phone`,`email`,`password`,`type`,`store_name`,`store_type`,`avatar`,`city`,`area`,`address`,`otp_code`,`otp_expires_at`,`fcm_token`,`is_verified`,`is_active`,`last_login_at`,`remember_token`,`created_at`,`updated_at`,`deleted_at`) VALUES ('5','سالم_customer','772000001',NULL,'$2y$12$Pm01k9Wv8lEaiybQqLpPqevdTY/U7hUpd647qGk8MjhyjU5YUFjje','customer',NULL,NULL,NULL,'صنعاء','السبعين',NULL,NULL,NULL,NULL,'1','1',NULL,NULL,'2026-07-25 01:25:39','2026-07-25 01:25:39',NULL);
INSERT INTO `users` (`id`,`name`,`phone`,`email`,`password`,`type`,`store_name`,`store_type`,`avatar`,`city`,`area`,`address`,`otp_code`,`otp_expires_at`,`fcm_token`,`is_verified`,`is_active`,`last_login_at`,`remember_token`,`created_at`,`updated_at`,`deleted_at`) VALUES ('6','فاطمة_customer','772000002',NULL,'$2y$12$eNm2dd2PHBkr30R6km5A8.tuY/i8FeHBddUP.OSgWl/A8KZ48O52e','customer',NULL,NULL,NULL,'عدن','المعلا',NULL,NULL,NULL,NULL,'1','1',NULL,NULL,'2026-07-25 01:25:40','2026-07-25 01:25:40',NULL);
INSERT INTO `users` (`id`,`name`,`phone`,`email`,`password`,`type`,`store_name`,`store_type`,`avatar`,`city`,`area`,`address`,`otp_code`,`otp_expires_at`,`fcm_token`,`is_verified`,`is_active`,`last_login_at`,`remember_token`,`created_at`,`updated_at`,`deleted_at`) VALUES ('7','خالد_customer','772000003',NULL,'$2y$12$5M2A7/K9bdg0sjPUHo5myuYjrVBnKm5ffIa13c2U40uVQ0SeN5ExW','customer',NULL,NULL,NULL,'تعز','المدينة',NULL,NULL,NULL,NULL,'1','1',NULL,NULL,'2026-07-25 01:25:40','2026-07-25 01:25:40',NULL);
INSERT INTO `users` (`id`,`name`,`phone`,`email`,`password`,`type`,`store_name`,`store_type`,`avatar`,`city`,`area`,`address`,`otp_code`,`otp_expires_at`,`fcm_token`,`is_verified`,`is_active`,`last_login_at`,`remember_token`,`created_at`,`updated_at`,`deleted_at`) VALUES ('8','نورة_customer','772000004',NULL,'$2y$12$VdWB6AOPB9A6AbBFWAHZ9OAmwgdofeABGHY6umIpoSBGUOJKMATOS','customer',NULL,NULL,NULL,'الحديدة','الميناء',NULL,NULL,NULL,NULL,'1','1',NULL,NULL,'2026-07-25 01:25:40','2026-07-25 01:25:40',NULL);
INSERT INTO `users` (`id`,`name`,`phone`,`email`,`password`,`type`,`store_name`,`store_type`,`avatar`,`city`,`area`,`address`,`otp_code`,`otp_expires_at`,`fcm_token`,`is_verified`,`is_active`,`last_login_at`,`remember_token`,`created_at`,`updated_at`,`deleted_at`) VALUES ('9','يوسف_customer','772000005',NULL,'$2y$12$uL1iauDZKws5c5HvnnByiOrjNmxhz.IKbFV8kaLJuAwJ4DXNa7Osi','customer',NULL,NULL,NULL,'إب','المركز',NULL,NULL,NULL,NULL,'1','1',NULL,NULL,'2026-07-25 01:25:41','2026-07-25 01:25:41',NULL);

TRUNCATE TABLE `categories`;
INSERT INTO `categories` (`id`,`parent_id`,`name`,`name_en`,`slug`,`description`,`image`,`icon`,`sort_order`,`is_active`,`created_at`,`updated_at`) VALUES ('1',NULL,'مواد غذائية','Food','moad-ghthayy',NULL,NULL,'utensils','1','1','2026-07-25 01:25:41','2026-07-25 01:25:41');
INSERT INTO `categories` (`id`,`parent_id`,`name`,`name_en`,`slug`,`description`,`image`,`icon`,`sort_order`,`is_active`,`created_at`,`updated_at`) VALUES ('2',NULL,'مشروبات','Beverages','mshrobat',NULL,NULL,'cup','2','1','2026-07-25 01:25:41','2026-07-25 01:25:41');
INSERT INTO `categories` (`id`,`parent_id`,`name`,`name_en`,`slug`,`description`,`image`,`icon`,`sort_order`,`is_active`,`created_at`,`updated_at`) VALUES ('3',NULL,'منظفات','Cleaning','mnthfat',NULL,NULL,'broom','3','1','2026-07-25 01:25:41','2026-07-25 01:25:41');
INSERT INTO `categories` (`id`,`parent_id`,`name`,`name_en`,`slug`,`description`,`image`,`icon`,`sort_order`,`is_active`,`created_at`,`updated_at`) VALUES ('4',NULL,'عناية شخصية','Personal Care','aanay-shkhsy',NULL,NULL,'heart','4','1','2026-07-25 01:25:41','2026-07-25 01:25:41');
INSERT INTO `categories` (`id`,`parent_id`,`name`,`name_en`,`slug`,`description`,`image`,`icon`,`sort_order`,`is_active`,`created_at`,`updated_at`) VALUES ('5',NULL,'ألبان وأجبان','Dairy','alban-oagban',NULL,NULL,'cheese','5','1','2026-07-25 01:25:41','2026-07-25 01:25:41');
INSERT INTO `categories` (`id`,`parent_id`,`name`,`name_en`,`slug`,`description`,`image`,`icon`,`sort_order`,`is_active`,`created_at`,`updated_at`) VALUES ('6',NULL,'مخبوزات','Bakery','mkhbozat',NULL,NULL,'bread','6','1','2026-07-25 01:25:41','2026-07-25 01:25:41');
INSERT INTO `categories` (`id`,`parent_id`,`name`,`name_en`,`slug`,`description`,`image`,`icon`,`sort_order`,`is_active`,`created_at`,`updated_at`) VALUES ('7',NULL,'توابل وبهارات','Spices','toabl-obharat',NULL,NULL,'fire','7','1','2026-07-25 01:25:41','2026-07-25 01:25:41');
INSERT INTO `categories` (`id`,`parent_id`,`name`,`name_en`,`slug`,`description`,`image`,`icon`,`sort_order`,`is_active`,`created_at`,`updated_at`) VALUES ('8',NULL,'معلبات','Canned Food','maalbat',NULL,NULL,'can','8','1','2026-07-25 01:25:41','2026-07-25 01:25:41');
INSERT INTO `categories` (`id`,`parent_id`,`name`,`name_en`,`slug`,`description`,`image`,`icon`,`sort_order`,`is_active`,`created_at`,`updated_at`) VALUES ('9',NULL,'حلويات','Sweets','hloyat',NULL,NULL,'candy','9','1','2026-07-25 01:25:41','2026-07-25 01:25:41');
INSERT INTO `categories` (`id`,`parent_id`,`name`,`name_en`,`slug`,`description`,`image`,`icon`,`sort_order`,`is_active`,`created_at`,`updated_at`) VALUES ('10',NULL,'إلكترونيات','Electronics','alktronyat',NULL,NULL,'plug','10','1','2026-07-25 01:25:41','2026-07-25 01:25:41');

TRUNCATE TABLE `suppliers`;
INSERT INTO `suppliers` (`id`,`user_id`,`company_name`,`company_name_en`,`commercial_register`,`tax_number`,`logo`,`banner`,`description`,`min_order_amount`,`delivery_fee`,`free_delivery_threshold`,`delivery_time_hours`,`rating`,`total_ratings`,`total_orders`,`is_verified`,`is_active`,`working_hours`,`delivery_areas`,`payment_methods`,`created_at`,`updated_at`,`deleted_at`) VALUES ('1','2','سوبر ماركت الرائد',NULL,NULL,NULL,NULL,NULL,'سوبر ماركت شامل يقدم جميع المنتجات الغذائية واليومية بأسعار منافسة','2000','500','10000','24','0','0','0','1','1','{\`sat\`:\`08:00-22:00\`,\`sun\`:\`08:00-22:00\`,\`mon\`:\`08:00-22:00\`,\`tue\`:\`08:00-22:00\`,\`wed\`:\`08:00-22:00\`,\`thu\`:\`08:00-22:00\`,\`fri\`:\`14:00-22:00\`}','[\`\\u0635\\u0646\\u0639\\u0627\\u0621\`,\`\\u0623\\u0645\\u0627\\u0646\\u0629 \\u0627\\u0644\\u0639\\u0627\\u0635\\u0645\\u0629\`]',NULL,'2026-07-25 01:25:38','2026-07-25 01:25:41',NULL);
INSERT INTO `suppliers` (`id`,`user_id`,`company_name`,`company_name_en`,`commercial_register`,`tax_number`,`logo`,`banner`,`description`,`min_order_amount`,`delivery_fee`,`free_delivery_threshold`,`delivery_time_hours`,`rating`,`total_ratings`,`total_orders`,`is_verified`,`is_active`,`working_hours`,`delivery_areas`,`payment_methods`,`created_at`,`updated_at`,`deleted_at`) VALUES ('2','3','بقالة الخير',NULL,NULL,NULL,NULL,NULL,'بقالة متنوعة تخدم منطقة كريتر وعدن','1000','500','10000','24','0','0','0','1','1','{\`sat\`:\`07:00-23:00\`,\`sun\`:\`07:00-23:00\`,\`mon\`:\`07:00-23:00\`,\`tue\`:\`07:00-23:00\`,\`wed\`:\`07:00-23:00\`,\`thu\`:\`07:00-23:00\`,\`fri\`:\`13:00-23:00\`}','[\`\\u0639\\u062f\\u0646\`,\`\\u0643\\u0631\\u064a\\u062a\\u0631\`,\`\\u0627\\u0644\\u0645\\u0639\\u0644\\u0627\`]',NULL,'2026-07-25 01:25:39','2026-07-25 01:25:41',NULL);
INSERT INTO `suppliers` (`id`,`user_id`,`company_name`,`company_name_en`,`commercial_register`,`tax_number`,`logo`,`banner`,`description`,`min_order_amount`,`delivery_fee`,`free_delivery_threshold`,`delivery_time_hours`,`rating`,`total_ratings`,`total_orders`,`is_verified`,`is_active`,`working_hours`,`delivery_areas`,`payment_methods`,`created_at`,`updated_at`,`deleted_at`) VALUES ('3','4','مطعم اليمان',NULL,NULL,NULL,NULL,NULL,'مطعم يمني أصيل يقدم أشهى المأكولات التقليدية','3000','500','10000','24','0','0','0','1','1','{\`sat\`:\`10:00-23:00\`,\`sun\`:\`10:00-23:00\`,\`mon\`:\`10:00-23:00\`,\`tue\`:\`10:00-23:00\`,\`wed\`:\`10:00-23:00\`,\`thu\`:\`10:00-23:00\`,\`fri\`:\`12:00-23:00\`}','[\`\\u062a\\u0639\\u0632\`,\`\\u0627\\u0644\\u0645\\u062f\\u064a\\u0646\\u0629\`]',NULL,'2026-07-25 01:25:39','2026-07-25 01:25:42',NULL);

TRUNCATE TABLE `products`;
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('1','1','1','أرز بسمتي 5 كجم',NULL,'arz-bsmty-5-kgm-1',NULL,NULL,NULL,NULL,'3500',NULL,NULL,'كيس','1','1','200','10',NULL,NULL,NULL,NULL,'1','1','282','62','4.85','12',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:42','2026-07-25 01:25:42',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('2','2','1','زيت طبخ 1.5 لتر',NULL,'zyt-tbkh-15-ltr-2',NULL,NULL,NULL,NULL,'1800',NULL,NULL,'زجاجة','1','1','150','10',NULL,NULL,NULL,NULL,'1','1','381','27','3.76','30',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:42','2026-07-25 01:25:42',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('3','3','1','سكر 2 كجم',NULL,'skr-2-kgm-3',NULL,NULL,NULL,NULL,'1200',NULL,NULL,'كيس','1','1','300','10',NULL,NULL,NULL,NULL,'1','1','339','36','4.27','21',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:42','2026-07-25 01:25:42',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('4','1','1','دقيق 2 كجم',NULL,'dkyk-2-kgm-4',NULL,NULL,NULL,NULL,'900',NULL,NULL,'كيس','1','1','250','10',NULL,NULL,NULL,NULL,'1','1','143','63','3.94','1',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:42','2026-07-25 01:25:42',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('5','2','1','معكرونة 500جم',NULL,'maakron-500gm-5',NULL,NULL,NULL,NULL,'450',NULL,NULL,'علبة','1','1','500','10',NULL,NULL,NULL,NULL,'1','1','319','68','3.75','2',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:42','2026-07-25 01:25:42',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('6','3','2','مياه معدنية 1.5 لتر',NULL,'myah-maadny-15-ltr-6',NULL,NULL,NULL,NULL,'150',NULL,NULL,'زجاجة','1','1','1000','10',NULL,NULL,NULL,NULL,'1','0','458','96','3.88','10',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:42','2026-07-25 01:25:42',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('7','1','2','عصير برتقال 1 لتر',NULL,'aasyr-brtkal-1-ltr-7',NULL,NULL,NULL,NULL,'600',NULL,NULL,'كرتون','1','1','100','10',NULL,NULL,NULL,NULL,'1','0','96','87','4.45','20',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:42','2026-07-25 01:25:42',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('8','2','2','شاي أحمر 500جم',NULL,'shay-ahmr-500gm-8',NULL,NULL,NULL,NULL,'800',NULL,NULL,'علبة','1','1','200','10',NULL,NULL,NULL,NULL,'1','0','344','62','4.62','11',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:42','2026-07-25 01:25:42',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('9','3','2','قهوة يمنية 250جم',NULL,'kho-ymny-250gm-9',NULL,NULL,NULL,NULL,'2500',NULL,NULL,'علبة','1','1','50','10',NULL,NULL,NULL,NULL,'1','0','458','56','3.98','39',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:42','2026-07-25 01:25:42',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('10','1','2','مشروب غازي 330مل',NULL,'mshrob-ghazy-330ml-10',NULL,NULL,NULL,NULL,'200',NULL,NULL,'علبة','1','1','800','10',NULL,NULL,NULL,NULL,'1','0','196','44','3.48','47',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:42','2026-07-25 01:25:42',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('11','2','3','مسحوق غسيل 2 كجم',NULL,'mshok-ghsyl-2-kgm-11',NULL,NULL,NULL,NULL,'1500',NULL,NULL,'علبة','1','1','120','10',NULL,NULL,NULL,NULL,'1','0','410','69','4.32','25',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:42','2026-07-25 01:25:42',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('12','3','3','سائل تنظيف أرضيات 1 لتر',NULL,'sayl-tnthyf-ardyat-1-ltr-12',NULL,NULL,NULL,NULL,'700',NULL,NULL,'زجاجة','1','1','80','10',NULL,NULL,NULL,NULL,'1','0','74','76','3.98','8',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:42','2026-07-25 01:25:42',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('13','1','3','صابون أطباق 500مل',NULL,'sabon-atbak-500ml-13',NULL,NULL,NULL,NULL,'350',NULL,NULL,'زجاجة','1','1','200','10',NULL,NULL,NULL,NULL,'1','0','469','66','4.8','40',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:43','2026-07-25 01:25:43',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('14','2','4','شامبو 400مل',NULL,'shambo-400ml-14',NULL,NULL,NULL,NULL,'900',NULL,NULL,'زجاجة','1','1','60','10',NULL,NULL,NULL,NULL,'1','0','176','59','3.88','0',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:43','2026-07-25 01:25:43',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('15','3','4','معجون أسنان 100مل',NULL,'maagon-asnan-100ml-15',NULL,NULL,NULL,NULL,'400',NULL,NULL,'أنبوب','1','1','150','10',NULL,NULL,NULL,NULL,'1','0','96','69','3.18','26',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:43','2026-07-25 01:25:43',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('16','1','4','صابون وجه 100جم',NULL,'sabon-ogh-100gm-16',NULL,NULL,NULL,NULL,'300',NULL,NULL,'قطعة','1','1','200','10',NULL,NULL,NULL,NULL,'1','0','333','97','4.86','10',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:43','2026-07-25 01:25:43',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('17','2','5','حليب طويل الأمد 1 لتر',NULL,'hlyb-toyl-alamd-1-ltr-17',NULL,NULL,NULL,NULL,'650',NULL,NULL,'كرتون','1','1','300','10',NULL,NULL,NULL,NULL,'1','0','418','58','4.5','31',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:43','2026-07-25 01:25:43',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('18','3','5','جبنة بيضاء 500جم',NULL,'gbn-bydaaa-500gm-18',NULL,NULL,NULL,NULL,'1200',NULL,NULL,'علبة','1','1','80','10',NULL,NULL,NULL,NULL,'1','0','276','28','4.43','30',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:43','2026-07-25 01:25:43',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('19','1','5','زبادي 170جم',NULL,'zbady-170gm-19',NULL,NULL,NULL,NULL,'200',NULL,NULL,'كوب','1','1','400','10',NULL,NULL,NULL,NULL,'1','0','158','65','4.66','43',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:43','2026-07-25 01:25:43',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('20','2','5','زبدة 250جم',NULL,'zbd-250gm-20',NULL,NULL,NULL,NULL,'800',NULL,NULL,'علبة','1','1','60','10',NULL,NULL,NULL,NULL,'1','0','272','59','4.47','13',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:43','2026-07-25 01:25:43',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('21','3','6','خبز عربي',NULL,'khbz-aarby-21',NULL,NULL,NULL,NULL,'100',NULL,NULL,'كيس','1','1','500','10',NULL,NULL,NULL,NULL,'1','0','65','8','4.2','25',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:43','2026-07-25 01:25:43',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('22','1','6','كعك 6 قطع',NULL,'kaak-6-ktaa-22',NULL,NULL,NULL,NULL,'500',NULL,NULL,'كيس','1','1','200','10',NULL,NULL,NULL,NULL,'1','0','104','31','4.17','41',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:43','2026-07-25 01:25:43',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('23','2','7','فلفل أسود 100جم',NULL,'flfl-asod-100gm-23',NULL,NULL,NULL,NULL,'400',NULL,NULL,'علبة','1','1','100','10',NULL,NULL,NULL,NULL,'1','0','86','20','3.4','45',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:43','2026-07-25 01:25:43',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('24','3','7','كمون 100جم',NULL,'kmon-100gm-24',NULL,NULL,NULL,NULL,'300',NULL,NULL,'علبة','1','1','120','10',NULL,NULL,NULL,NULL,'1','0','410','100','3.91','11',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:43','2026-07-25 01:25:43',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('25','1','7','هيل 50جم',NULL,'hyl-50gm-25',NULL,NULL,NULL,NULL,'600',NULL,NULL,'علبة','1','1','80','10',NULL,NULL,NULL,NULL,'1','0','66','31','3.93','28',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:43','2026-07-25 01:25:43',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('26','2','8','تونة 185جم',NULL,'ton-185gm-26',NULL,NULL,NULL,NULL,'500',NULL,NULL,'علبة','1','1','300','10',NULL,NULL,NULL,NULL,'1','0','342','67','3.43','41',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:43','2026-07-25 01:25:43',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('27','3','8','حمص مسلوق 400جم',NULL,'hms-mslok-400gm-27',NULL,NULL,NULL,NULL,'350',NULL,NULL,'علبة','1','1','200','10',NULL,NULL,NULL,NULL,'1','0','302','10','3.9','30',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:44','2026-07-25 01:25:44',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('28','1','8','صلصة طماطم 400جم',NULL,'sls-tmatm-400gm-28',NULL,NULL,NULL,NULL,'250',NULL,NULL,'علبة','1','1','400','10',NULL,NULL,NULL,NULL,'1','0','25','29','4.28','46',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:44','2026-07-25 01:25:44',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('29','2','9','شوكولاتة 100جم',NULL,'shokolat-100gm-29',NULL,NULL,NULL,NULL,'600',NULL,NULL,'قطعة','1','1','150','10',NULL,NULL,NULL,NULL,'1','0','322','60','4.28','30',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:44','2026-07-25 01:25:44',NULL);
INSERT INTO `products` (`id`,`supplier_id`,`category_id`,`name`,`name_en`,`slug`,`description`,`description_en`,`sku`,`barcode`,`price`,`compare_price`,`cost_price`,`unit`,`unit_quantity`,`min_order_quantity`,`stock_quantity`,`low_stock_threshold`,`weight`,`weight_unit`,`images`,`thumbnail`,`is_active`,`is_featured`,`views_count`,`sales_count`,`rating`,`total_ratings`,`tags`,`attributes`,`expiry_date`,`manufacturer`,`country_of_origin`,`created_at`,`updated_at`,`deleted_at`) VALUES ('30','3','9','بسكويت 200جم',NULL,'bskoyt-200gm-30',NULL,NULL,NULL,NULL,'350',NULL,NULL,'علبة','1','1','200','10',NULL,NULL,NULL,NULL,'1','0','414','60','5','17',NULL,NULL,NULL,NULL,NULL,'2026-07-25 01:25:44','2026-07-25 01:25:44',NULL);

SET FOREIGN_KEY_CHECKS=1;
